Traceback (most recent call last):
  File "/home/hs20307/tls-rl/rl.py", line 154, in <module>
    main()
  File "/home/hs20307/tls-rl/rl.py", line 109, in main
    logits = get_logits(observation, args.nfirst)
  File "/home/hs20307/tls-rl/rl.py", line 75, in get_logits
    logits = actor.forward(input_ids=encoder_input_ids, decoder_input_ids=decoder_input_ids).logits  # state
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 1278, in forward
    outputs = self.model(
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 1144, in forward
    encoder_outputs = self.encoder(
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 769, in forward
    layer_outputs = encoder_layer(
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 330, in forward
    hidden_states = self.fc2(hidden_states)
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/hs20307/.conda/envs/env/lib/python3.9/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.76 GiB total capacity; 9.13 GiB already allocated; 5.44 MiB free; 9.58 GiB reserved in total by PyTorch)

